-- Up
CREATE TABLE IF NOT EXISTS url_types (
  type_id INT AUTO_INCREMENT PRIMARY KEY,
  url_type VARCHAR(50) NOT NULL UNIQUE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- Down
DROP TABLE IF EXISTS url_types;  